const githubResult = '''
{
  "total_count": 14473,
  "incomplete_results": false,
  "items": [
    {
      "login": "thiago",
      "id": 1700827,
      "node_id": "MDQ6VXNlcjE3MDA4Mjc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1700827?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiago",
      "html_url": "https://github.com/thiago",
      "followers_url": "https://api.github.com/users/thiago/followers",
      "following_url": "https://api.github.com/users/thiago/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiago/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiago/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiago/subscriptions",
      "organizations_url": "https://api.github.com/users/thiago/orgs",
      "repos_url": "https://api.github.com/users/thiago/repos",
      "events_url": "https://api.github.com/users/thiago/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiago/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagofa",
      "id": 797053,
      "node_id": "MDQ6VXNlcjc5NzA1Mw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/797053?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagofa",
      "html_url": "https://github.com/thiagofa",
      "followers_url": "https://api.github.com/users/thiagofa/followers",
      "following_url": "https://api.github.com/users/thiagofa/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagofa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagofa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagofa/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagofa/orgs",
      "repos_url": "https://api.github.com/users/thiagofa/repos",
      "events_url": "https://api.github.com/users/thiagofa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagofa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ThiagoBarradas",
      "id": 12145276,
      "node_id": "MDQ6VXNlcjEyMTQ1Mjc2",
      "avatar_url": "https://avatars1.githubusercontent.com/u/12145276?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ThiagoBarradas",
      "html_url": "https://github.com/ThiagoBarradas",
      "followers_url": "https://api.github.com/users/ThiagoBarradas/followers",
      "following_url": "https://api.github.com/users/ThiagoBarradas/following{/other_user}",
      "gists_url": "https://api.github.com/users/ThiagoBarradas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ThiagoBarradas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ThiagoBarradas/subscriptions",
      "organizations_url": "https://api.github.com/users/ThiagoBarradas/orgs",
      "repos_url": "https://api.github.com/users/ThiagoBarradas/repos",
      "events_url": "https://api.github.com/users/ThiagoBarradas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ThiagoBarradas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagopnts",
      "id": 322239,
      "node_id": "MDQ6VXNlcjMyMjIzOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/322239?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagopnts",
      "html_url": "https://github.com/thiagopnts",
      "followers_url": "https://api.github.com/users/thiagopnts/followers",
      "following_url": "https://api.github.com/users/thiagopnts/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagopnts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagopnts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagopnts/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagopnts/orgs",
      "repos_url": "https://api.github.com/users/thiagopnts/repos",
      "events_url": "https://api.github.com/users/thiagopnts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagopnts/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagomarquessp",
      "id": 5871971,
      "node_id": "MDQ6VXNlcjU4NzE5NzE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5871971?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagomarquessp",
      "html_url": "https://github.com/thiagomarquessp",
      "followers_url": "https://api.github.com/users/thiagomarquessp/followers",
      "following_url": "https://api.github.com/users/thiagomarquessp/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagomarquessp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagomarquessp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagomarquessp/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagomarquessp/orgs",
      "repos_url": "https://api.github.com/users/thiagomarquessp/repos",
      "events_url": "https://api.github.com/users/thiagomarquessp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagomarquessp/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagommedeiros",
      "id": 19213244,
      "node_id": "MDQ6VXNlcjE5MjEzMjQ0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/19213244?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagommedeiros",
      "html_url": "https://github.com/thiagommedeiros",
      "followers_url": "https://api.github.com/users/thiagommedeiros/followers",
      "following_url": "https://api.github.com/users/thiagommedeiros/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagommedeiros/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagommedeiros/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagommedeiros/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagommedeiros/orgs",
      "repos_url": "https://api.github.com/users/thiagommedeiros/repos",
      "events_url": "https://api.github.com/users/thiagommedeiros/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagommedeiros/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoyama",
      "id": 5407309,
      "node_id": "MDQ6VXNlcjU0MDczMDk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5407309?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoyama",
      "html_url": "https://github.com/thiagoyama",
      "followers_url": "https://api.github.com/users/thiagoyama/followers",
      "following_url": "https://api.github.com/users/thiagoyama/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoyama/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoyama/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoyama/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoyama/orgs",
      "repos_url": "https://api.github.com/users/thiagoyama/repos",
      "events_url": "https://api.github.com/users/thiagoyama/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoyama/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ThiagoAGDev",
      "id": 1707249,
      "node_id": "MDQ6VXNlcjE3MDcyNDk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1707249?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ThiagoAGDev",
      "html_url": "https://github.com/ThiagoAGDev",
      "followers_url": "https://api.github.com/users/ThiagoAGDev/followers",
      "following_url": "https://api.github.com/users/ThiagoAGDev/following{/other_user}",
      "gists_url": "https://api.github.com/users/ThiagoAGDev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ThiagoAGDev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ThiagoAGDev/subscriptions",
      "organizations_url": "https://api.github.com/users/ThiagoAGDev/orgs",
      "repos_url": "https://api.github.com/users/ThiagoAGDev/repos",
      "events_url": "https://api.github.com/users/ThiagoAGDev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ThiagoAGDev/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoloureiro",
      "id": 29433794,
      "node_id": "MDQ6VXNlcjI5NDMzNzk0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/29433794?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoloureiro",
      "html_url": "https://github.com/thiagoloureiro",
      "followers_url": "https://api.github.com/users/thiagoloureiro/followers",
      "following_url": "https://api.github.com/users/thiagoloureiro/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoloureiro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoloureiro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoloureiro/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoloureiro/orgs",
      "repos_url": "https://api.github.com/users/thiagoloureiro/repos",
      "events_url": "https://api.github.com/users/thiagoloureiro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoloureiro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagolioy",
      "id": 1314052,
      "node_id": "MDQ6VXNlcjEzMTQwNTI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1314052?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagolioy",
      "html_url": "https://github.com/thiagolioy",
      "followers_url": "https://api.github.com/users/thiagolioy/followers",
      "following_url": "https://api.github.com/users/thiagolioy/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagolioy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagolioy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagolioy/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagolioy/orgs",
      "repos_url": "https://api.github.com/users/thiagolioy/repos",
      "events_url": "https://api.github.com/users/thiagolioy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagolioy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagolunardi",
      "id": 5428523,
      "node_id": "MDQ6VXNlcjU0Mjg1MjM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5428523?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagolunardi",
      "html_url": "https://github.com/thiagolunardi",
      "followers_url": "https://api.github.com/users/thiagolunardi/followers",
      "following_url": "https://api.github.com/users/thiagolunardi/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagolunardi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagolunardi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagolunardi/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagolunardi/orgs",
      "repos_url": "https://api.github.com/users/thiagolunardi/repos",
      "events_url": "https://api.github.com/users/thiagolunardi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagolunardi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagolima-bm",
      "id": 4673405,
      "node_id": "MDQ6VXNlcjQ2NzM0MDU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/4673405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagolima-bm",
      "html_url": "https://github.com/thiagolima-bm",
      "followers_url": "https://api.github.com/users/thiagolima-bm/followers",
      "following_url": "https://api.github.com/users/thiagolima-bm/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagolima-bm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagolima-bm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagolima-bm/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagolima-bm/orgs",
      "repos_url": "https://api.github.com/users/thiagolima-bm/repos",
      "events_url": "https://api.github.com/users/thiagolima-bm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagolima-bm/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagopradi",
      "id": 6090,
      "node_id": "MDQ6VXNlcjYwOTA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6090?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagopradi",
      "html_url": "https://github.com/thiagopradi",
      "followers_url": "https://api.github.com/users/thiagopradi/followers",
      "following_url": "https://api.github.com/users/thiagopradi/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagopradi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagopradi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagopradi/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagopradi/orgs",
      "repos_url": "https://api.github.com/users/thiagopradi/repos",
      "events_url": "https://api.github.com/users/thiagopradi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagopradi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagomanel",
      "id": 217297,
      "node_id": "MDQ6VXNlcjIxNzI5Nw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/217297?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagomanel",
      "html_url": "https://github.com/thiagomanel",
      "followers_url": "https://api.github.com/users/thiagomanel/followers",
      "following_url": "https://api.github.com/users/thiagomanel/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagomanel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagomanel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagomanel/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagomanel/orgs",
      "repos_url": "https://api.github.com/users/thiagomanel/repos",
      "events_url": "https://api.github.com/users/thiagomanel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagomanel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagocaiubi",
      "id": 15719,
      "node_id": "MDQ6VXNlcjE1NzE5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/15719?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagocaiubi",
      "html_url": "https://github.com/thiagocaiubi",
      "followers_url": "https://api.github.com/users/thiagocaiubi/followers",
      "following_url": "https://api.github.com/users/thiagocaiubi/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagocaiubi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagocaiubi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagocaiubi/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagocaiubi/orgs",
      "repos_url": "https://api.github.com/users/thiagocaiubi/repos",
      "events_url": "https://api.github.com/users/thiagocaiubi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagocaiubi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ThiagoFerreir4",
      "id": 10325354,
      "node_id": "MDQ6VXNlcjEwMzI1MzU0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/10325354?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ThiagoFerreir4",
      "html_url": "https://github.com/ThiagoFerreir4",
      "followers_url": "https://api.github.com/users/ThiagoFerreir4/followers",
      "following_url": "https://api.github.com/users/ThiagoFerreir4/following{/other_user}",
      "gists_url": "https://api.github.com/users/ThiagoFerreir4/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ThiagoFerreir4/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ThiagoFerreir4/subscriptions",
      "organizations_url": "https://api.github.com/users/ThiagoFerreir4/orgs",
      "repos_url": "https://api.github.com/users/ThiagoFerreir4/repos",
      "events_url": "https://api.github.com/users/ThiagoFerreir4/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ThiagoFerreir4/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagolocatelli",
      "id": 1017031,
      "node_id": "MDQ6VXNlcjEwMTcwMzE=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1017031?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagolocatelli",
      "html_url": "https://github.com/thiagolocatelli",
      "followers_url": "https://api.github.com/users/thiagolocatelli/followers",
      "following_url": "https://api.github.com/users/thiagolocatelli/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagolocatelli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagolocatelli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagolocatelli/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagolocatelli/orgs",
      "repos_url": "https://api.github.com/users/thiagolocatelli/repos",
      "events_url": "https://api.github.com/users/thiagolocatelli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagolocatelli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "tgmarinho",
      "id": 380327,
      "node_id": "MDQ6VXNlcjM4MDMyNw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/380327?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tgmarinho",
      "html_url": "https://github.com/tgmarinho",
      "followers_url": "https://api.github.com/users/tgmarinho/followers",
      "following_url": "https://api.github.com/users/tgmarinho/following{/other_user}",
      "gists_url": "https://api.github.com/users/tgmarinho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tgmarinho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tgmarinho/subscriptions",
      "organizations_url": "https://api.github.com/users/tgmarinho/orgs",
      "repos_url": "https://api.github.com/users/tgmarinho/repos",
      "events_url": "https://api.github.com/users/tgmarinho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tgmarinho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagorondon",
      "id": 122926,
      "node_id": "MDQ6VXNlcjEyMjkyNg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/122926?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagorondon",
      "html_url": "https://github.com/thiagorondon",
      "followers_url": "https://api.github.com/users/thiagorondon/followers",
      "following_url": "https://api.github.com/users/thiagorondon/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagorondon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagorondon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagorondon/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagorondon/orgs",
      "repos_url": "https://api.github.com/users/thiagorondon/repos",
      "events_url": "https://api.github.com/users/thiagorondon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagorondon/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagocdn",
      "id": 61380775,
      "node_id": "MDQ6VXNlcjYxMzgwNzc1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/61380775?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagocdn",
      "html_url": "https://github.com/thiagocdn",
      "followers_url": "https://api.github.com/users/thiagocdn/followers",
      "following_url": "https://api.github.com/users/thiagocdn/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagocdn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagocdn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagocdn/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagocdn/orgs",
      "repos_url": "https://api.github.com/users/thiagocdn/repos",
      "events_url": "https://api.github.com/users/thiagocdn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagocdn/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagopaiva99",
      "id": 20430611,
      "node_id": "MDQ6VXNlcjIwNDMwNjEx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/20430611?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagopaiva99",
      "html_url": "https://github.com/thiagopaiva99",
      "followers_url": "https://api.github.com/users/thiagopaiva99/followers",
      "following_url": "https://api.github.com/users/thiagopaiva99/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagopaiva99/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagopaiva99/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagopaiva99/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagopaiva99/orgs",
      "repos_url": "https://api.github.com/users/thiagopaiva99/repos",
      "events_url": "https://api.github.com/users/thiagopaiva99/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagopaiva99/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagozs",
      "id": 140747,
      "node_id": "MDQ6VXNlcjE0MDc0Nw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/140747?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagozs",
      "html_url": "https://github.com/thiagozs",
      "followers_url": "https://api.github.com/users/thiagozs/followers",
      "following_url": "https://api.github.com/users/thiagozs/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagozs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagozs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagozs/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagozs/orgs",
      "repos_url": "https://api.github.com/users/thiagozs/repos",
      "events_url": "https://api.github.com/users/thiagozs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagozs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagofm",
      "id": 126355,
      "node_id": "MDQ6VXNlcjEyNjM1NQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/126355?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagofm",
      "html_url": "https://github.com/thiagofm",
      "followers_url": "https://api.github.com/users/thiagofm/followers",
      "following_url": "https://api.github.com/users/thiagofm/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagofm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagofm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagofm/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagofm/orgs",
      "repos_url": "https://api.github.com/users/thiagofm/repos",
      "events_url": "https://api.github.com/users/thiagofm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagofm/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagokimo",
      "id": 1932485,
      "node_id": "MDQ6VXNlcjE5MzI0ODU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1932485?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagokimo",
      "html_url": "https://github.com/thiagokimo",
      "followers_url": "https://api.github.com/users/thiagokimo/followers",
      "following_url": "https://api.github.com/users/thiagokimo/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagokimo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagokimo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagokimo/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagokimo/orgs",
      "repos_url": "https://api.github.com/users/thiagokimo/repos",
      "events_url": "https://api.github.com/users/thiagokimo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagokimo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoghisi",
      "id": 270128,
      "node_id": "MDQ6VXNlcjI3MDEyOA==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/270128?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoghisi",
      "html_url": "https://github.com/thiagoghisi",
      "followers_url": "https://api.github.com/users/thiagoghisi/followers",
      "following_url": "https://api.github.com/users/thiagoghisi/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoghisi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoghisi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoghisi/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoghisi/orgs",
      "repos_url": "https://api.github.com/users/thiagoghisi/repos",
      "events_url": "https://api.github.com/users/thiagoghisi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoghisi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagohersan",
      "id": 850815,
      "node_id": "MDQ6VXNlcjg1MDgxNQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/850815?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagohersan",
      "html_url": "https://github.com/thiagohersan",
      "followers_url": "https://api.github.com/users/thiagohersan/followers",
      "following_url": "https://api.github.com/users/thiagohersan/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagohersan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagohersan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagohersan/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagohersan/orgs",
      "repos_url": "https://api.github.com/users/thiagohersan/repos",
      "events_url": "https://api.github.com/users/thiagohersan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagohersan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "trennepohl",
      "id": 12124856,
      "node_id": "MDQ6VXNlcjEyMTI0ODU2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/12124856?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/trennepohl",
      "html_url": "https://github.com/trennepohl",
      "followers_url": "https://api.github.com/users/trennepohl/followers",
      "following_url": "https://api.github.com/users/trennepohl/following{/other_user}",
      "gists_url": "https://api.github.com/users/trennepohl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/trennepohl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/trennepohl/subscriptions",
      "organizations_url": "https://api.github.com/users/trennepohl/orgs",
      "repos_url": "https://api.github.com/users/trennepohl/repos",
      "events_url": "https://api.github.com/users/trennepohl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/trennepohl/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoxvo",
      "id": 37016,
      "node_id": "MDQ6VXNlcjM3MDE2",
      "avatar_url": "https://avatars3.githubusercontent.com/u/37016?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoxvo",
      "html_url": "https://github.com/thiagoxvo",
      "followers_url": "https://api.github.com/users/thiagoxvo/followers",
      "following_url": "https://api.github.com/users/thiagoxvo/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoxvo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoxvo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoxvo/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoxvo/orgs",
      "repos_url": "https://api.github.com/users/thiagoxvo/repos",
      "events_url": "https://api.github.com/users/thiagoxvo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoxvo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoralves",
      "id": 8240060,
      "node_id": "MDQ6VXNlcjgyNDAwNjA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8240060?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoralves",
      "html_url": "https://github.com/thiagoralves",
      "followers_url": "https://api.github.com/users/thiagoralves/followers",
      "following_url": "https://api.github.com/users/thiagoralves/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoralves/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoralves/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoralves/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoralves/orgs",
      "repos_url": "https://api.github.com/users/thiagoralves/repos",
      "events_url": "https://api.github.com/users/thiagoralves/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoralves/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mrprompt",
      "id": 166088,
      "node_id": "MDQ6VXNlcjE2NjA4OA==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/166088?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mrprompt",
      "html_url": "https://github.com/mrprompt",
      "followers_url": "https://api.github.com/users/mrprompt/followers",
      "following_url": "https://api.github.com/users/mrprompt/following{/other_user}",
      "gists_url": "https://api.github.com/users/mrprompt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mrprompt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mrprompt/subscriptions",
      "organizations_url": "https://api.github.com/users/mrprompt/orgs",
      "repos_url": "https://api.github.com/users/mrprompt/repos",
      "events_url": "https://api.github.com/users/mrprompt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mrprompt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
''';
